# Gradle settings for the entire project.
# For IDE users (e.g., Android Studio):
# Any Gradle settings configured through the IDE *will override*
# those specified in this file.
# For more information on setting up your build environment, visit:
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM options used by the Gradle daemon.
# This setting is particularly useful for customizing memory allocation.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enables Gradle's experimental parallel build mode when set.
# Use this option only with independent projects.
# For more details, visit:
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true

# The AndroidX package structure distinguishes system packages bundled with
# the Android OS from those packaged within your app's APK.
# For more information, visit:
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true

# Kotlin code style for this project: options are "official" or "obsolete".
kotlin.code.style=official

# Enables non-transitive R classes for each library, which means that each library’s
# R class will only include resources declared within that library, excluding its dependencies.
# This reduces the size of each library's R class.
android.nonTransitiveRClass=true

# Marvel API keys for accessing Marvel's public and private data
MARVEL_PUBLIC_KEY=40194719adab64b889291299fc5e457e
MARVEL_PRIVATE_KEY=afd8f5333f37f4ede639520016ffc134e4783339
